image: node:18.18.0

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: Build and Test Node
              caches:
                - node
              script:
                - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" != "main" ] && [ "$BITBUCKET_PR_DESTINATION_BRANCH" != "develop" ]; then echo 'Destination not main or develop branch.'; exit 0; fi
                - apt-get update
                - node -v
                - python3 --version
                - npm install
                - npm run build
                - npx jest
          - step:
              name: Code linting Node
              caches:
                - node
              script:
                - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" != "main" ] && [ "$BITBUCKET_PR_DESTINATION_BRANCH" != "develop" ]; then echo 'Destination not main or develop branch.'; exit 0; fi
                - npm install
                - npm run lint:js || true

  custom: 
    manual-trigger:
      - parallel:
          - step:
              name: Manually Triggered Build and Test Node
              script:
                - apt-get update
                - node -v
                - python3 --version
                - npm install
                - npm run build
                - npx jest
          - step:
              name: Manually Triggered Node Code linting
              script:
                - npm install
                - npm run lint:js || true