@startuml SD Lv1

participant "Campus Manager" as campusManager
participant RobDroneGo as system
campusManager -> system : open route
activate system

system -> system : get list of all buildings

campusManager <--o system : show list of all buildings

campusManager -> system : select building

system -> system : get list of all floors\nof that buildings

campusManager <--o system : show list of all floors

campusManager -> system : select floors

campusManager -> system : input elevator information

system -> system : create elevator

campusManager <--o system : elevator created successfully

deactivate system

@enduml