@startuml SD Lv2

participant "Campus Management" as campusManager
box "RobDroneGo" #LightBlue
    participant "Campus Management UI" as campusUI
    participant "Campus Management API" as campusAPI
    participant "DB" as DB
end box

campusManager -> campusUI : open route (buildingCode)
activate campusUI

        campusUI -> campusAPI : list floors with passages to diferent buildings
        activate campusAPI
    
        campusAPI -> DB : get passages with buildingCode
        activate DB
        DB --> campusAPI : list passages
        deactivate DB
    
        campusAPI -> DB : get floors of the passages
        activate DB
        DB --> campusAPI : list of floors
        deactivate DB
    
        campusAPI --> campusUI : list of floors
        deactivate campusAPI
    
campusManager <-- campusUI : show list of floors
deactivate campusUI

@enduml