@startuml SD Lv3

!pragma teoz true

participant " "
box "Campus Management" #LightBlue

    box "Framework And Drivers Layer" #00ffff
        participant Routing
        participant "Building Persistence" as Persistence
        participant "Floor Persistence" as FloorPers
    end box

    participant "Data Model" as Data
    box "Interface Adapters Layer" #77ffaa
        participant Controller
        participant "Building Repository" as Repository
        participant "Floor Repository" as FloorRepo
    end box

    participant "Elevator DTO" as DTO
    participant "Building DTO" as BuildingDTO
    participant "Elevator Mapper" as Mapper
    participant "Building Mapper" as BuildingMapper
    box "Application Business Rules" #ff6666
        participant "Elevator Service" as ElevatorService
    end box

    box "Enterprise Business Rules" #eeddaa
        participant Building
        participant Elevator
        participant Floor
    end box
end box


[o-> Routing : Post
activate Routing

    Routing -> Controller : createElevator(input)
    activate Controller

        Controller -> DTO : input as DTO
        activate DTO

        DTO --> Controller : elevatorDTO
        deactivate DTO

        Controller -> ElevatorService : createElevator(elevatorDTO, code, floors)
        activate ElevatorService
        
            ElevatorService -> Repository : findByCode(code)
            activate Repository

                Repository -> Persistence : findByCode(code)
                activate Persistence

                Persistence --> Repository : building
                deactivate Persistence

            Repository --> ElevatorService : building
            deactivate Repository

            ElevatorService -> FloorRepo : findByCodes(building, codes)
            activate FloorRepo

                FloorRepo -> FloorPers : findByCodes(building, codes)
                activate FloorPers

                FloorPers --> FloorRepo : floors
                deactivate FloorPers

            FloorRepo --> ElevatorService : floors
            deactivate FloorRepo

            ElevatorService -> Elevator : create(...)
            activate Elevator

            Elevator --> ElevatorService : elevator
            deactivate Elevator

            ElevatorService -> Building : set elevator = elevator
            activate Building
            
            Building --> ElevatorService : Success
            deactivate Building

            loop for each floor
                ElevatorService -> Floor : servedByElevator = true
                activate Floor
                Floor --> ElevatorService : Success
                deactivate Floor
            end

            ElevatorService -> Repository : save(building)
            activate Repository

                Repository -> Persistence : save(building)
                activate Persistence

                Persistence --> Repository : Success
                deactivate Persistence

            Repository --> ElevatorService : Success
            deactivate Repository

            ElevatorService -> FloorRepo : save(floors)
            activate FloorRepo

                FloorRepo -> FloorPers : save(floors)
                activate FloorPers

                FloorPers --> FloorRepo : Success
                deactivate FloorPers

            FloorRepo --> ElevatorService : Success
            deactivate FloorRepo

        ElevatorService -> BuildingMapper : toDTO(building)
        activate BuildingMapper

            BuildingMapper -> Mapper : toDTO(elevator)
            activate Mapper

                Mapper -> DTO : elevator as DTO
                activate DTO

                DTO --> Mapper: elevatorDTO
                deactivate DTO

            Mapper --> BuildingMapper : elevatorDTO
            deactivate Mapper

            
                BuildingMapper -> BuildingDTO : building as DTO
                activate BuildingDTO

                BuildingDTO --> BuildingMapper: buildingDTO
                deactivate BuildingDTO
        
        BuildingMapper --> ElevatorService : buildingDTO
        deactivate BuildingMapper

        ElevatorService --> Controller : buildingDTO
        deactivate ElevatorService

    Controller --> Routing : buildingDTO
    deactivate Controller

[o<--o Routing : buildingDTO
deactivate Routing


@enduml