@startuml Logical_View_Lv2

<style>
component {
    BackgroundColor #99ddff
}
</style>

interface "Campus API" as campus_API
interface "Fleet API" as fleet_API
interface "Task API" as task_API
interface "User API" as user_API
' interface "Planning API" as planning_API
interface "UI API" as UI_API

component RobDroneGo {
    component "Campus Management" as campus
    component "Fleet Management" as fleet
    component "Task Management" as task
    component "Planning Module" as planning


    campus -0)- planning
    fleet -0)- planning
    task -(0- planning

    component "User Management" as user
    component UI

    UI -(0- campus
    UI -(0- fleet
    UI -(0- task
    UI -(0- planning
    UI -(0- user

    ' component "DMS" as dms
    ' dms -0)- fleet
    ' dms -0)- task
    ' dms -0)- campus
}
fleet -down- fleet_API
campus -up- campus_API
task -down- task_API
user -down- user_API
' planning -down- planning_API
UI -up- UI_API

@enduml