@startuml SD Lv1

participant RobDroneGo as system
[o-> system : Put (oldPassageinfo\nnewPassageInfo)
activate system

system -> system : Update passage \nto new info

[o<--o system : Passage
deactivate system

@enduml