@startuml SD Lv1

participant "RobDroneGo" as System

[o-> System : GET /building/:code/elevators
activate System

System -> System : Retrieve Elevators in Building

[o<--o System : List of Elevators
deactivate System

@enduml
