@startuml SD Lv1

participant RobDroneGo as system
[o-> system : Get (buildingCode)
activate system

system -> system : Query passages with \nbuildingCode and diffrent ones 

[o<--o system : Floors
deactivate system

@enduml