image: node:18.18.0

pipelines:
  branches:
    main:
      - step:
          name: "Build and Test"
          caches:
            - node
          script:
            - npm install
            - npm run build -- --configuration production
            - echo DeploymentToken
            - echo $deployment_token
          artifacts:
            - dist/dronesangularclient/**
      - step:
          name: "Deploy to Azure Static Web Apps"
          script:
            - pipe: microsoft/azure-static-web-apps-deploy:main
              variables:
                APP_LOCATION: '/'
                OUTPUT_LOCATION: 'dist/dronesangularclient'
                #ARTIFACT_LOCATION: 'dist/dronesangularclient'
                AZURE_STATIC_WEB_APPS_API_TOKEN: 'ef22040f662896b525659c6d1e5fc6752d631afc0172763b6ba97d179d2745af4-270374ce-b7be-4705-8bd6-d634d04d7c11003310767'

