image: node:18.18.0

pipelines:
  branches:
    main:
      - step:
          name: "Build and Test"
          caches:
            - node
          script:
            - npm install
            #- npm run test
            - npm run build -- --configuration production
          artifacts:
            - dist/dronesangularclient/**
      - step:
          name: "Deploy to Azure Static Web Apps"
          script:
            - npm install -g @azure/static-web-apps-cli
            - swa deploy dist/dronesangularclient --deployment-token $SWA_DEPLOYMENT_TOKEN