@startuml SD Lv1

participant "Campus Management System" as system

[o-> system : GET /passages?building1={code1}\n\t&building2={code2}
activate system

alt if passages exist between buildings
    system -> system : Retrieve passages
    [o<--o system : passages list
else
    [o<--o system : empty list
end

deactivate system

@enduml
