@startuml SD Lv2

participant "Client" as Client
box "Campus Management System" #LightBlue
    participant "Campus Management" as Campus
    participant "DB" as DB
end box

Client -> Campus : GET /passages?building1={code1}\n\t&building2={code2}
activate Campus

Campus -> DB : find passages between code1 and code2
activate DB
DB --> Campus : list of passages / empty
deactivate DB

alt if passages exist
    Client <-- Campus : passages list
else
    Client <-- Campus : empty list
end

deactivate Campus

@enduml
