@startuml SD Lv2

box "Robot Management" #LightBlue
    participant "Robot Service" as RobotService
    participant "Database" as DB
end box

[o-> RobotService : GET /robot?query
activate RobotService

RobotService -> DB : find robots by type query
activate DB
DB --> RobotService : robots list
deactivate DB

[o<--o RobotService : robots list
deactivate RobotService

@enduml
