@startuml SD Lv3

!pragma teoz true

participant " "
box "Campus Management" #LightBlue

    box "Framework And Drivers Layer" #00ffff
        participant Routing
        participant "Floor Persistence" as Schema
    end box

    box "Interface Adapters Layer" #77ffaa
        participant Controller
        participant "Floor Repository" as Repository
    end box

    participant DTO
    participant "Floor Mapper" as Map
    box "Application Business Rules" #ff6666
        participant "Floor Service" as Service
    end box

end box


[o-> Routing : Get
activate Routing

    Routing -> Controller : create()
    activate Controller
    Routing -> Controller : getFloorByBuildingCode(buildingCode))

        Controller -> Service : getFloorByBuildingCode(buildingCode))
        activate Service
            Service -> Repository : findByBuildingCode(buildingCode)
            activate Repository
                Repository -> Schema : find(query)
                Schema --> Repository : floors

                    Repository -> Map : toDomain(floors)
                    activate Map
                        Map --> Repository : floorRecords
                    deactivate Map
                Repository --> Service : floorRecords
            deactivate Repository
            loop for each floor
                Service -> Map : toDTO(floor)
                Map --> Service : floorDTO
            end
            Service --> Controller :  Result.ok<IFloorDTO[]>(floorDTOs)
        deactivate Service

    Controller --> Routing : res.status(200).json(floorDTOs)
    deactivate Controller

[o<--o Routing : List of floors
deactivate Routing


@enduml