@startuml SD Lv2

participant " "
box "RobDroneGo" #LightBlue
    participant "Campus Management" as campus
    participant "DB" as DB
end box

[o-> campus : Put (oldPassageinfo\nnewPassageInfo)
activate campus

campus -> DB : load passage
activate DB
DB --> campus : passage
deactivate DB

campus -> DB : validate floors
activate DB
DB --> campus : floors
deactivate DB

campus -> campus: update passage\nto newPassageInfo

campus -> DB : save passage
activate DB
DB --> campus : passage
deactivate DB

[o<--o campus : passage
deactivate campus

@enduml