@startuml SD Lv2

actor "Campus Management" as user
box "RobDroneGo" #LightBlue
participant "UI" as ui
    participant "Campus Management" as campus
    participant "DB" as DB
end box

user -> ui : enter URL

activate ui
ui -> campus : request buildings info
activate campus

campus -> DB : find buildings
activate DB
DB --> campus : buildings
deactivate DB

ui <-- campus : List with buildings
deactivate campus

ui --> user : show buildings
deactivate ui
@enduml