@startuml SD Lv1

participant RobDroneGo as system
[o-> system : POST /building
activate system

system -> system : Check building already exists

alt same building does not exist

    system -> system : Save new building

    [o<--o system : building result
    
else if building with code exists

    [o<--o system : error message

end
deactivate system

@enduml
