@startuml SD Lv1

participant RobDroneGo as system
[o-> system : Post (robot type info)
activate system

system -> system : Create and Save\nrobot type

[o<--o system : Success
deactivate system

@enduml